version: '3.4'

services:    
  EkmobDb:
    container_name: EkmobDb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"

  ekmob.technical.customer:
    container_name: EkmobTech
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://EkmobDb:27017"
    depends_on: 
      - EkmobDb
    ports:
      - "5001:80"